config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?


  resources :complex_tasks
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/complex_task.rb
class ComplexTask < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/complex_tasks_controller.rb
class ComplexTasksController < ApplicationController
  before_action :set_complex_task, only: [:show, :edit, :update, :destroy]

  # GET /complex_tasks
  # GET /complex_tasks.json
  def index
    @complex_tasks = ComplexTask.all
  end

  # GET /complex_tasks/1
  # GET /complex_tasks/1.json
  def show
  end

  # GET /complex_tasks/new
  def new
    @complex_task = ComplexTask.new
  end

  # GET /complex_tasks/1/edit
  def edit
  end

  # POST /complex_tasks
  def create
    @complex_task = ComplexTask.new(complex_task_params)
    @complex_task.result = "not computed yet."
    if @complex_task.save
      # enqueue job
      ComplexTaskJob.perform_later(@complex_task)
      redirect_to @complex_task, notice: 'Complex task was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /complex_tasks/1
  # PATCH/PUT /complex_tasks/1.json
  def update
    respond_to do |format|
      if @complex_task.update(complex_task_params)
        format.html { redirect_to @complex_task, notice: 'Complex task was successfully updated.' }
        format.json { render :show, status: :ok, location: @complex_task }
      else
        format.html { render :edit }
        format.json { render json: @complex_task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /complex_tasks/1
  # DELETE /complex_tasks/1.json
  def destroy
    @complex_task.destroy
    respond_to do |format|
      format.html { redirect_to complex_tasks_url, notice: 'Complex task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_complex_task
      @complex_task = ComplexTask.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def complex_task_params
      params.require(:complex_task).permit(:title, :result)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/complex_tasks_helper.rb
module ComplexTasksHelper
end

app/views/complex_tasks/_form.html.erb
<%= form_with(model: complex_task, local: true) do |form| %>
  <% if complex_task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(complex_task.errors.count, "error") %> prohibited this complex_task from being saved:</h2>

      <ul>
        <% complex_task.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :result %>
    <%= form.text_area :result %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/complex_tasks/edit.html.erb
<h1>Editing Complex Task</h1>

<%= render 'form', complex_task: @complex_task %>

<%= link_to 'Show', @complex_task %> |
<%= link_to 'Back', complex_tasks_path %>

app/views/complex_tasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Complex Tasks</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Result</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @complex_tasks.each do |complex_task| %>
      <tr>
        <td><%= complex_task.title %></td>
        <td><%= complex_task.result %></td>
        <td><%= link_to 'Show', complex_task %></td>
        <td><%= link_to 'Edit', edit_complex_task_path(complex_task) %></td>
        <td><%= link_to 'Destroy', complex_task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Complex Task', new_complex_task_path %>

app/views/complex_tasks/new.html.erb
<h1>New Complex Task</h1>

<%= render 'form', complex_task: @complex_task %>

<%= link_to 'Back', complex_tasks_path %>

app/views/complex_tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @complex_task.title %>
</p>

<p>
  <strong>Result:</strong>
  <%= @complex_task.result %>
</p>

<%= link_to 'Edit', edit_complex_task_path(@complex_task) %> |
<%= link_to 'Back', complex_tasks_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Vagrant</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>